version: '3'

services:
  
  node:
    image: node:16.14
    container_name: food_delivery
    tty: true
    stdin_open: true
    restart: always
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=${MONGO_URL}
    
  mongodb:
    image: mongo:5.0.7
    container_name: food_delivery_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
    default:
      name: food_delivery_net